default: &default
  adapter: postgresql
  encoding: unicode
  # encoding: utf8
  # username: postgres
  # password: root
  # template: template1
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
production:
  <<: *default
  username: deploy
  password: India4@)
  database: online_jewellery_development
development:
  <<: *default
  database: online_jewellery_development